### ISSUE TITLE
Porting to Typescript 

### ISSUE THREAD

**Issue by azzamsa** [sveltejs/realworld#119] opened 2022-07-28 09:26 UTC
Hi.

It is the good place to start reading and learning Svelte. Is there any plan to port it to Typescript so we know the best practice too?

Such how to organize types and maximize the use of `app.d.ts`.

**Comment by benmccann** [comment] 2022-11-03 17:39
duplicate of https://github.com/sveltejs/realworld/issues/89

**Closed by benmccann** 2022-11-03 17:39 UTC
